### ISSUE TITLE
Flathub site doesn't get updated after 1.13.0 version

### ISSUE THREAD

**Issue by Chilledheart** [flathub/io.github.chilledheart.yass#4]
Yass is new to flathub and just added in https://github.com/flathub/flathub/pull/5486 last week.

I managed to update 1.12.3 version sucessfully but the flathub site doesn't get updated after 24 hrs of #3 and it still shows 1.12.3.

Is it a bug or caused by other issues?

@bbhtt @Khalif12321 @barthalion 

Thanks!

**Comment by bbhtt** [comment]
Yes there is an infrastructure issue going on, we are looking into it.

**Comment by Chilledheart** [comment]
Thanks for the quick reply @bbhtt! Please let me know if there is anything I can help.

**Comment by bbhtt** [comment]
we fixed the infra issue and looks like you started a manual rebuild.

It's queued to be published in an hour https://buildbot.flathub.org/#/builders/6/builds/141399

Website might need some time to update due to the Fastly cache.

**Comment by Chilledheart** [comment]
Thanks for informing of the fix of infrastructure issues. It looks like the new version is available on the flathub website.

**Comment by Chilledheart** [comment]
Close this issue as the infrastucture failure has been resolved.
